import Foundation

/// Concrete model for known booster `contents` keys found across your uploaded files.
/// (No Dictionary properties.)
public struct MTGJSONBoosterContents: Codable, Sendable {
    public var arcaneMischief: Int?
    public var arcaneMischiefFoils: Int?
    public var basic: Int?
    public var beastTerritory: Int?
    public var beastTerritoryFoils: Int?
    public var celestialBasicLand: Int?
    public var coalitionCorps: Int?
    public var coalitionCorpsFoils: Int?
    public var coalitionLegion: Int?
    public var coalitionLegionFoils: Int?
    public var commander: Int?
    public var commanderCard: Int?
    public var common: Int?
    public var commonUncommonBorderless: Int?
    public var commonUncommonRetro: Int?
    public var commonUncommonShowcase: Int?
    public var commonWithDuplicates: Int?
    public var etchedRetoldRareMythic: Int?
    public var etchedRetoldUncommon: Int?
    public var extendedRareMythic: Int?
    public var foil: Int?
    public var foilAltBorderRareMythic: Int?
    public var foilBasic: Int?
    public var foilBoosterfun: Int?
    public var foilCommander: Int?
    public var foilCommon: Int?
    public var foilCommonUncommonShowcase: Int?
    public var foilFullartLand: Int?
    public var foilLand: Int?
    public var foilLegendsRetold: Int?
    public var foilRare: Int?
    public var foilRareMythic: Int?
    public var foilRareMythicShowcase: Int?
    public var foilShowcaseRareMythic: Int?
    public var foilStellarSightsLand: Int?
    public var foilUncommon: Int?
    public var foilUncommonShowcase: Int?
    public var foilWithShowcase: Int?
    public var galaxyStellarSightsLand: Int?
    public var land: Int?
    public var legendaryRareMythic: Int?
    public var legendaryUncommon: Int?
    public var lostLegends: Int?
    public var monsterTerritory: Int?
    public var monsterTerritoryFoils: Int?
    public var mysticMischief: Int?
    public var mysticMischiefFoils: Int?
    public var nonFoilBoosterfun: Int?
    public var nonfoilRareMythic: Int?
    public var nonlegendaryRareMythic: Int?
    public var nonlegendaryUncommon: Int?
    public var prereleasePromo: Int?
    public var rare: Int?
    public var rareMythic: Int?
    public var rareMythicBlack: Int?
    public var rareMythicBlue: Int?
    public var rareMythicGreen: Int?
    public var rareMythicRed: Int?
    public var rareMythicWhite: Int?
    public var rareMythicWithShowcase: Int?
    public var rareMythicWithShowcaseOrBorderless: Int?
    public var retroCommander: Int?
    public var retroNonlegendaryRareMythic: Int?
    public var retroRareMythic: Int?
    public var retroUncommon: Int?
    public var showcaseRareMythic: Int?
    public var showcaseUncommon: Int?
    public var special: Int?
    public var starterDeckRare: Int?
    public var stellarSightsLand: Int?
    public var texturedFoil: Int?
    public var theList: Int?
    public var totallyMerciless: Int?
    public var totallyMercilessFoils: Int?
    public var totallyRuthless: Int?
    public var totallyRuthlessFoils: Int?
    public var uncommon: Int?
    public var uncommonShowcase: Int?
    public var uncommonWithDuplicates: Int?
    public var wildcard: Int?
}
