import Foundation

struct MTGJsonCard: Decodable {
    let artist: String?
    let artistIds: [String]?
    let availability: [String]?
    let boosterTypes: [String]?
    let borderColor: String?
    let colorIdentity: [String]?
    let colors: [String]?
    let convertedManaCost: Double?
    let edhrecRank: Int?
    let edhrecSaltiness: Double?
    let finishes: [String]?
    let flavorText: String?
    let foreignData: [MTGJsonForeignData]?
    let frameVersion: String?
    let hasFoil: Bool?
    let hasNonFoil: Bool?
    let identifiers: MTGJsonCardIdentifiers?
    let isReprint: Bool?
    let keywords: [String]?
    let language: String?
    let layout: String?
    let legalities: MTGJsonLegalities?
    let manaCost: String?
    let manaValue: Double?
    let name: String?
    let number: String?
    let originalText: String?
    let power: String?
    let printings: [String]?
    let purchaseUrls: MTGJsonPurchaseUrls?
    let rarity: String?
    let setCode: String?
    let subtypes: [String]?
    let supertypes: [String]?
    let text: String?
    let toughness: String?
    let type: String?
    let types: [String]?
    let uuid: String?
    let variations: [String]?
    let securityStamp: String?
    let rulings: [MTGJsonRuling]?
    let promoTypes: [String]?
    let frameEffects: [String]?
    let leadershipSkills: MTGJsonLeadershipSkills?   // CHANGED: was [String]?
    let loyalty: String?
    let isAlternative: Bool?
    let isPromo: Bool?
    let isFullArt: Bool?
    let watermark: String?
    let side: String?
    let faceConvertedManaCost: Double?
    let faceName: String?
    let otherFaceIds: [String]?
    let faceManaValue: Double?
    let isOnlineOnly: Bool?
    let isFunny: Bool?
    let isTextless: Bool?
    let duelDeck: String?
    let originalReleaseDate: String?
    let relatedCards: [String: [String]]? 
    let isOversized: Bool?
    let asciiName: String?
    let isStorySpotlight: Bool?
    let defense: String?
    let signature: String?
    let colorIndicator: [String]?
    let isReserved: Bool?
    let hasContentWarning: Bool?
    let isGameChanger: Bool?
    let isTimeshifted: Bool?
    let hasAlternativeDeckLimit: Bool?
    let rebalancedPrintings: [String]?
    let originalPrintings: [String]?
    let isRebalanced: Bool?
    let flavorName: String?
    let faceFlavorName: String?
    let cardParts: [String]?
    let life: String?
    let hand: String?
    let subsets: [String]?
}
