import Foundation

struct MTGJsonToken: Decodable {
    let name: String?
    let uuid: String?
    let type: String?
    let text: String?
    let power: String?
    let toughness: String?
    let colors: [String]?
    let setCode: String?
    let artist: String?
    let identifiers: [String: String]?
    let borderColor: String?
    let faceName: String?
    let edhrecSaltiness: Double?
    let number: String?
    let reverseRelated: [String]?
    let supertypes: [String]?
    let frameVersion: String?
    let finishes: [String]?
    let hasNonFoil: Bool?
    let layout: String?
    let hasFoil: Bool?
    let orientation: String?
    let subtypes: [String]?
    let colorIdentity: [String]?
    let artistIds: [String]?
    let otherFaceIds: [String]?
    let types: [String]?
    let side: String?
    let signature: String?
    let language: String?
    let availability: [String]?
    let isReprint: Bool?
    let relatedCards: [String: [String]]?   // CHANGED from [String]?
    let promoTypes: [String]?
    let isPromo: Bool?
    let isFullArt: Bool?
    let isAlternative: Bool?
    let isTextless: Bool?
    let isOversized: Bool?
    let isGameChanger: Bool?
    let isFunny: Bool?
    let isReserved: Bool?
    let isOnlineOnly: Bool?
    let isPartialPreview: Bool?
    let isStarter: Bool?
    let isRebalanced: Bool?
    let rebalancedPrintings: [String]?
    let originalPrintings: [String]?
    let flavorText: String?
    let flavorName: String?
    let faceFlavorName: String?
    let asciiName: String?
    let leadershipSkills: [String]?
    let loyalty: String?
    let defense: String?
    let life: String?
    let hand: String?
    let attractionLights: [String]?
    let subsets: [String]?
    let cardParts: [String]?
    let watermarks: [String]?
    let securityStamp: String?
    let duelDeck: String?
    let originalReleaseDate: String?
    let printings: [String]?
    let variations: [String]?
    let sourceProducts: [String]?
    let mcmIdExtras: String?
    let mcmId: String?
    let mcmName: String?
    let tcgplayerGroupId: String?
    let cardsphereSetId: String?
    let parentCode: String?
    let tokenSetCode: String?
    let translations: [String: String]?
    let keyruneCode: String?
    let releaseDate: String?
    let block: String?
    let baseSetSize: Int?
    let totalSetSize: Int?
    let mtgoCode: String?
    let isFoilOnly: Bool?
    let isNonFoilOnly: Bool?
    let isForeignOnly: Bool?
    let decks: [String: String]?
    let keywords: [String]?
    let boosterTypes: [String]?
    let frameEffects: [String]?
    let manaCost: String?
    let originalText: String?
    let watermark: String?
}
