import Foundation

struct MTGJsonBooster: Decodable {
    let prereleaseSilumgar: MTGJsonBoosterMode?
    let prereleaseKolaghan: MTGJsonBoosterMode?
    let prereleaseDromoka: MTGJsonBoosterMode?
    let prereleaseOjutai: MTGJsonBoosterMode?
    let prereleaseAtarka: MTGJsonBoosterMode?
    let themeNinjas: MTGJsonBoosterMode?
    let draft: MTGJsonBoosterMode?
    let `default`: MTGJsonBoosterMode?
    let arena: MTGJsonBoosterMode?
    let prerelease: MTGJsonBoosterMode?
    let collector: MTGJsonBoosterMode?
    let fatPack: MTGJsonBoosterMode?
    let starter: MTGJsonBoosterMode?
    let vip: MTGJsonBoosterMode?
    let boxTopper: MTGJsonBoosterMode?
    let play: MTGJsonBoosterMode?
    let mtgo: MTGJsonBoosterMode?
    let themeAzorius: MTGJsonBoosterMode?
    let themeGruul: MTGJsonBoosterMode?
    let themeSimic: MTGJsonBoosterMode?
    let themeOrzhov: MTGJsonBoosterMode?
    let themeRakdos: MTGJsonBoosterMode?
    let themeGolgari: MTGJsonBoosterMode?
    let themeIzzet: MTGJsonBoosterMode?
    let themeBoros: MTGJsonBoosterMode?
    let themeSelesnya: MTGJsonBoosterMode?
    let themeDimir: MTGJsonBoosterMode?
    let prereleaseAzorius: MTGJsonBoosterMode?
    let prereleaseSelesnya: MTGJsonBoosterMode?
    let prereleaseIzzet: MTGJsonBoosterMode?
    let prereleaseGolgari: MTGJsonBoosterMode?
    let prereleaseRakdos: MTGJsonBoosterMode?
    let prereleaseDimir: MTGJsonBoosterMode?
    let prereleaseOrzhov: MTGJsonBoosterMode?
    let prereleaseSimic: MTGJsonBoosterMode?
    let prereleaseGruul: MTGJsonBoosterMode?
    let prereleaseBoros: MTGJsonBoosterMode?
    let collectorSample: MTGJsonBoosterMode?
    let themeB: MTGJsonBoosterMode?
    let themeG: MTGJsonBoosterMode?
    let themeW: MTGJsonBoosterMode?
    let themeR: MTGJsonBoosterMode?
    let themeU: MTGJsonBoosterMode?
    let collectorJp: MTGJsonBoosterMode?
    let themeMonsters: MTGJsonBoosterMode?
    let themeWerewolves: MTGJsonBoosterMode?
    let duelspromo: MTGJsonBoosterMode?
    let stainedglassR: MTGJsonBoosterMode?
    let deceptiveDistricts: MTGJsonBoosterMode?
    let blueprintMk1: MTGJsonBoosterMode?
    let stainedglassG: MTGJsonBoosterMode?
    let finElementals: MTGJsonBoosterMode?
    let stainedglassU: MTGJsonBoosterMode?
    let stainedglassIwd: MTGJsonBoosterMode?
    let stainedglassC: MTGJsonBoosterMode?
    let stainedglassUncommon: MTGJsonBoosterMode?
    let stainedglassB: MTGJsonBoosterMode?
    let blueprintMk2: MTGJsonBoosterMode?
    let chaosEmeralds: MTGJsonBoosterMode?
    let stainedglassTattoo: MTGJsonBoosterMode?
    let stainedglassW: MTGJsonBoosterMode?
    let convention: MTGJsonBoosterMode?
    let convention2021: MTGJsonBoosterMode?
    let beginner: MTGJsonBoosterMode?
    let compleat: MTGJsonBoosterMode?
    let jumpstartV2: MTGJsonBoosterMode?
    let collectorSpecial: MTGJsonBoosterMode?
    let playArena: MTGJsonBoosterMode?
    let arena1: MTGJsonBoosterMode?
    let arena2: MTGJsonBoosterMode?
    let arena3: MTGJsonBoosterMode?
    let arena4: MTGJsonBoosterMode?
    let themeVikings: MTGJsonBoosterMode?
    let themeSilverquill: MTGJsonBoosterMode?
    let themeLorehold: MTGJsonBoosterMode?
    let jp: MTGJsonBoosterMode?
    let themePrismari: MTGJsonBoosterMode?
    let setJp: MTGJsonBoosterMode?
    let themeQuandrix: MTGJsonBoosterMode?
    let themeWitherbloom: MTGJsonBoosterMode?
    let themeVampires: MTGJsonBoosterMode?
    let treasureChest: MTGJsonBoosterMode?
    let premium: MTGJsonBoosterMode?
    let boxTopperFoil: MTGJsonBoosterMode?
    let giftBundlePromo: MTGJsonBoosterMode?
    let bundlePromo: MTGJsonBoosterMode?
    let jumpstart: MTGJsonBoosterMode?
    let set: MTGJsonBoosterMode?
    let themeParty: MTGJsonBoosterMode?
    let themeDungeons: MTGJsonBoosterMode?
    let themeMaestros: MTGJsonBoosterMode?
    let themeBrokers: MTGJsonBoosterMode?
    let themeCabaretti: MTGJsonBoosterMode?
    let themeRiveteers: MTGJsonBoosterMode?
    let themeObscura: MTGJsonBoosterMode?
    let prereleaseRiveteers: MTGJsonBoosterMode?
    let prereleaseObscura: MTGJsonBoosterMode?
    let prereleaseMaestros: MTGJsonBoosterMode?
    let prereleaseCabaretti: MTGJsonBoosterMode?
    let prereleaseBrokers: MTGJsonBoosterMode?
    let tournament: MTGJsonBoosterMode?
    let six: MTGJsonBoosterMode?
}
